### ISSUE TITLE
Add typespecs

### ISSUE THREAD

**Issue by PragTob** [PragTob/deep_merge#3]
Enough said, wanna be a good dialyzer citizen - especially for such a small library :)

**Comment by sotojuan** [comment]
For `deep_merge(original, override)` would it be:

```elixir
@spec deep_merge(map | list(tuple), map | list(tuple)) :: map
```
? If so we can add a type (not sure under what name) that represents either a `map` or `list(tuple)`. I'm fairly new to typespecs so there may be a better thing we can use.

**Comment by PragTob** [comment]
I'm not quite sure myself yet :D but yes, we should add/use a type that is map and list together and it takes these and returns them. So in your sample the return type should also be map union list. :)

**Comment by PragTob** [comment]
They are on master now
